//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultantVisit
    {
        public int ConsultantVisitId { get; set; }
        public int ConsultantID { get; set; }
        public System.DateTime Consultationdate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
