//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationFee
    {
        public int ConsultationID { get; set; }
        public int DoctorID { get; set; }
        public int ConsultTypeID { get; set; }
        public Nullable<decimal> Fee { get; set; }
    
        public virtual User User { get; set; }
        public virtual ConsultationType ConsultationType { get; set; }
    }
}
