//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCollection
    {
        public int FeeID { get; set; }
        public string ENMRNO { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaidOn { get; set; }
        public string Purpose { get; set; }
        public string PaymentMode { get; set; }
    
        public virtual InPatient InPatient { get; set; }
    }
}
