//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabKitItem
    {
        public int LKitItemID { get; set; }
        public int LKitID { get; set; }
        public int TestID { get; set; }
    
        public virtual TestType TestType { get; set; }
    }
}
