//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineInventory
    {
        public int MedInventoryID { get; set; }
        public int MedicineID { get; set; }
        public Nullable<int> AvailableQty { get; set; }
        public Nullable<decimal> PricePerItem { get; set; }
    
        public virtual MedicineMaster MedicineMaster { get; set; }
    }
}
