//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInsurance
    {
        public int FileID { get; set; }
        public string FileNo { get; set; }
        public string ENMRNO { get; set; }
        public decimal QuotedAmount { get; set; }
        public Nullable<decimal> GrantedAmount { get; set; }
    }
}
