//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMetric
    {
        public int SNO { get; set; }
        public string ENMRNO { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public Nullable<int> HeartBeat { get; set; }
        public Nullable<decimal> BP { get; set; }
        public Nullable<decimal> Temperature { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
