//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRoomAllocation
    {
        public int AllocationID { get; set; }
        public string ENMRNO { get; set; }
        public int RoomNo { get; set; }
        public int BrandID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Room Room { get; set; }
    }
}
