//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitHistory
    {
        public int SNO { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public int ConsultTypeID { get; set; }
        public string ENMRNO { get; set; }
        public decimal FEE { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> PatientType { get; set; }
    
        public virtual ConsultationType ConsultationType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
