//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPrescription
    {
        public int MedicineID { get; set; }
        public int Quantity { get; set; }
        public int IntakeFrequencyID { get; set; }
        public string Comments { get; set; }
        public string BatchNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> DeliverQty { get; set; }
        public int PTID { get; set; }
        public int PMID { get; set; }
    
        public virtual IntakeFrequency IntakeFrequency { get; set; }
        public virtual MedicineMaster MedicineMaster { get; set; }
        public virtual PrescriptionMaster PrescriptionMaster { get; set; }
    }
}
