//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int OrderID { get; set; }
        public string PONumber { get; set; }
        public int MedicineID { get; set; }
        public int OrderedQty { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public Nullable<decimal> PricePerItem { get; set; }
        public Nullable<decimal> PricePerSheet { get; set; }
        public string BatchNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
    
        public virtual MedicineMaster MedicineMaster { get; set; }
    }
}
