//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.PatientRoomAllocations = new HashSet<PatientRoomAllocation>();
            this.Beds = new HashSet<Bed>();
        }
    
        public int RoomNo { get; set; }
        public string RoomName { get; set; }
        public int RoomTypeID { get; set; }
        public string Description { get; set; }
        public int CostPerDay { get; set; }
        public Nullable<int> RoomStatus { get; set; }
        public Nullable<System.DateTime> NextAvailbility { get; set; }
        public Nullable<int> RoomBedCapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientRoomAllocation> PatientRoomAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bed> Beds { get; set; }
    }
}
