//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanCategory
    {
        public int SCID { get; set; }
        public string Category { get; set; }
        public int ScanID { get; set; }
    
        public virtual Scan Scan { get; set; }
    }
}
